### ISSUE TITLE
When running script, screen is blank

### ISSUE THREAD

**Issue by joveaaron** [vimpop/pcf8574-linux#1]
All characters are white and nothing happens. The screen appears to get initialized, but as I said the screen gets filled with blank characters (all pixels are on)

**Comment by vimpop** [comment]
what's the backpack module that you are using?

**Comment by joveaaron** [comment]
I don't know it exactly, but it looks very similar to the one on the drawing

**Comment by joveaaron** [comment]
On the backpack it says HW-061

**Comment by vimpop** [comment]
The initialization sequence should set all pixels to 0, may sound a bit trivial but try adjusting the contrast knob if that fails, then try the following code, it should set the cursor and turn blinking on. If that works then one of the signal lanes is swapped on the backpack. 
https://gist.github.com/vimpop/9be0b80c6bd595cec56cacada8f009ff

**Comment by joveaaron** [comment]
It does the same thing

**Comment by joveaaron** [comment]
I have tried to adjust the contrast knob. All it does is hide or show the characters

**Comment by vimpop** [comment]
Oh, well does the display work with a Arduino? If it does, what library did you use ?

**Comment by joveaaron** [comment]
The last time I tried to use it worked. I guess that I can try it with an Arduino.

**Comment by vimpop** [comment]
One more thing, does address show up in ```i2cdetect```? 
Test this by first connecting the display and running the ```i2cdetect``` command, see if anything popped up.Then remove the display and run ```i2cdetect``` again, if its gone then you found the address

**Comment by joveaaron** [comment]
It does show up. One thing you said on the README.MD file about two addresses but in my case, only one shows up. Is that an issue?

**Comment by vimpop** [comment]
Not sure, it could either be scanning quirk which may or may not cause an issue, though i cannot write to the 3e address. 
You could try the following code that will toggle the LED back light at one second intervals, if that fails then there is some wiring issue or worst case, some driver issue. 
https://gist.github.com/vimpop/b82989042e557b60f0330645db16f58f

**Comment by joveaaron** [comment]
I've got another computer and when trying the blinking LCD cursor, it works. when connecting my VGA cable to the older one and trying to run the exact same code with the exact same parameters, it initializes it but the cursor doesn't show up.

**Comment by joveaaron** [comment]
I am running Ubuntu 14.04 Trusty LTS on the one that isn't working and Ubuntu 18.04.6 LTS on the one that is working. Both computers' python3s are up-to-date and the code is the same.

**Comment by joveaaron** [comment]
Also, is it possible to add custom characters functionality? And is it possible to send a specific character to the display? I am trying to make a gauge for this display and I was able to make it on Arduino but I don't know how here.

**Comment by vimpop** [comment]
Ah, Ubuntu 14.04 - yeah have not tested that(probably never) since i last tested this on ubuntu 20.04 and i see no reason to get this working on such a outdated version. 
> is it possible to add custom characters functionality? 
>  is it possible to send a specific character to the display?

Yes, you need to use the [datasheet](https://www.crystalfontz.com/controllers/Hitachi/HD44780/97/) which references this functionality but ideally you would want to use a library and port that over to your usage instead of reinventing the wheel as this is just a basic example that exposes the simplest instructions to the display

**Comment by joveaaron** [comment]
Are there any libraries that support this LCD over VGA I2C at all? I will be very surprised if they are. * quick google search * Oh. My. God. I found some code that will do it ALL. I was indeed very surprised! Thank you for your help! I'll try that code tomorrow.
